### ISSUE TITLE
Install failure - TypeError in pycommand.py

### ISSUE THREAD

**Issue by TheGreatFox** [joselado/quantum-honeycomp#1]
**Issue:** 
When installing quantum-honeycomp following the instructions in the README, installer fails with the following:
`File "../Downloads/quantum-honeycomp/pysrc/interpreter/pycommand.py", line 48, in install_dependencies`
`os.system(pip+" install "+l) # install this library`
`TypeError: unsupported operand type(s) for +: 'Nonetype' and 'str'`

**Additional info:**
- OS: Ubuntu 20.04 LTS
- Updates: New virtual machine and all package updates applied
- It appears that you are calling pip using a method not recommended by the developer. See additional information here: https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program.
- See additional info here: https://stackoverflow.com/questions/12332975/installing-python-module-within-code

**Comment by TheGreatFox** [comment]
Follow-up:
This same error is also seen for Ubuntu 18.04.3 LTS (fresh installation). 
This only appears on new installations. An existing installation on an old VM of 18.04 updates correctly, as this process does not depend on the installer (git pull).

**Comment by joselado** [comment]
Thanks TheGreatFox for the note, I just did an update now, now it should install correctly.

**Comment by TheGreatFox** [comment]
Addressed the installer issue, but brings up a bad python interpreter issue now for a fresh install. Opening another bug since the installer issue was resolved.
