### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by TheGreatFox** [joselado/quantum-honeycomp#2]
**Issue:** 
After downloading and installing quantum-honeycomp, there is the following error at execution:
`bash: ../Downloads/quantum-honeycomp/psyrc/interpreter/../../bin/quantum-honeycomp: /usr/bin/python: bad interpreter: No such file or directory`

**Further Information:**
OS: Ubuntu 18.04.3 LTS (fresh installation)
Aliasing python = python3 still allows for the installer to install, but running `quantum-honeycomp` will yield the error `command not found`. Directly executing the binary `./bin/quantum-honeycomp` again results in `command not found`.

**Comment by joselado** [comment]
Thanks TheGreatFox for the comment! I just updated the code, now it should work.
