### ISSUE TITLE
Dependency requirements - Ubuntu 20.04

### ISSUE THREAD

**Issue by TheGreatFox** [joselado/quantum-honeycomp#3]
**Issue:** 
Clarify the dependency requirements for Ubuntu 20.04+, which no longer contains Python 2.

**Details:**
User should be told to install the following applications before proceeding with QH installation:
 - git
 - gfortran
 - python-is-python3

python-is-python3 will address the temporary issue of still issuing Python 2 commands, by linking them to the correct Python 3 interpreter.

**Comment by TheGreatFox** [comment]
Will update these after a check with anaconda pre-installed, so don't close yet.

**Comment by joselado** [comment]
Hi TheGreatFox, I just made an update addressing these issues. 
python-is-python3 is no longer required
gfortran is also not required
git is still required, but only for updates (not to install the code)

I tested the installer in a fresh Ubuntu 20 installation and it works.

**Comment by TheGreatFox** [comment]
Functions correctly now on Ubuntu 20.04 based on the latest commits.
