### ISSUE TITLE
QH Installation - Multiprocessing no longer required in Python 3

### ISSUE THREAD

**Issue by TheGreatFox** [joselado/quantum-honeycomp#4]
**Issue:** 
Installer will show an error during installation of the multiprocessing module. 

`SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Macros:')`

**Further Information:**
Multiprocessing is built into Python since Python 2.6+ and is no longer needed. It could be safely removed unless otherwise needed for obsolete versions of Python (Python 2).

**Comment by joselado** [comment]
Thanks TheGreatFox, fixed!
